# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-server'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:9042']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
